// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// ris_recursion
NumericMatrix ris_recursion(int r, int NT, arma::mat BCH, arma::mat rand_mat, arma::vec V);
RcppExport SEXP _risprobit_ris_recursion(SEXP rSEXP, SEXP NTSEXP, SEXP BCHSEXP, SEXP rand_matSEXP, SEXP VSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type r(rSEXP);
    Rcpp::traits::input_parameter< int >::type NT(NTSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type BCH(BCHSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type rand_mat(rand_matSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type V(VSEXP);
    rcpp_result_gen = Rcpp::wrap(ris_recursion(r, NT, BCH, rand_mat, V));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_risprobit_ris_recursion", (DL_FUNC) &_risprobit_ris_recursion, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_risprobit(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
