# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ris_recursion <- function(r, NT, BCH, rand_mat, V) {
    .Call(`_risprobit_ris_recursion`, r, NT, BCH, rand_mat, V)
}

